# Site settings
author: Agnes 
title: BLog
header-img: img/home-bg.png
email: agnespark824@gmail.com
copyright_name: Agnes 
description: > # this means to ignore newlines until "baseurl:"
  blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  agnespark824

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
